-- 013_pricing_tiers.sql
-- Adds CMS keys for the 4-tier pricing presentation

INSERT INTO site_config (key, value, updated_by, updated_at) VALUES
  ('tiers_headline_pre', 'Pick your ', 'migration', NOW()),
  ('tiers_headline_gold', 'power.', 'migration', NOW()),
  ('tiers_subhead', 'Four systems, sized to your home. Every price is all-in — solar panels and installation included.', 'migration', NOW()),
  ('tiers_popular_label', 'Most Popular', 'migration', NOW()),
  ('tiers_disclaimer', 'These are starting estimates that include solar panels and installation. Every home is different — your exact price is locked in after a quick, free site inspection.', 'migration', NOW()),
  ('tiers_glossary_label', 'Solar terms, in plain English', 'migration', NOW()),
  ('pricing_tiers', '[{"name":"First Light","icon":"☀️","system":"12K single-zone mini-split","price":"$8,700–$9,500","coverage":"600–700 sq ft","panels":"3 solar panels","tagline":"One room, dialed in.","features":["1-ton single-zone unit","Best for your main living area","A couple of box fans spread comfort nicely","5-year warranty"],"popular":false},{"name":"Sunbeam","icon":"🌤️","system":"24K single-zone mini-split","price":"~$11,000","coverage":"1,000–1,350 sq ft","panels":"6 solar panels","tagline":"Hugo''s own setup.","features":["2-ton single-zone unit","Great for a large open living space","One powerful air handler","5-year warranty"],"popular":false},{"name":"High Noon","icon":"🔆","system":"24K multizone (2–3 heads)","price":"$12,000–$15,000","coverage":"1,250–1,500 sq ft","panels":"6–8 solar panels","tagline":"Whole-home comfort.","features":["Up to 3 independent air handlers (min. 2)","Living room + bedrooms on separate zones","Combined output up to 36K BTU","5-year warranty"],"popular":true},{"name":"Solar Flare","icon":"🌟","system":"36K multizone (2–4 heads)","price":"$13,500–$16,000","coverage":"1,500–2,000 sq ft","panels":"7–9 solar panels","tagline":"Maximum coverage.","features":["Up to 4 independent air handlers (min. 2)","Sized for larger multi-room homes","Combined output up to 40K BTU","5-year warranty"],"popular":false}]', 'migration', NOW()),
  ('tiers_glossary', '[{"term":"Mini-split","definition":"A ductless heating + cooling system. An outdoor unit connects to one or more indoor \"air handlers\" — no ductwork needed."},{"term":"Air handler (head)","definition":"The indoor wall unit that delivers heated or cooled air to a room. More heads = more rooms covered independently."},{"term":"Single-zone vs. multizone","definition":"Single-zone runs one air handler. Multizone runs several off one system, each controlled separately."},{"term":"BTU (12K / 24K / 36K)","definition":"A measure of heating/cooling power. 12K = 12,000 BTU ≈ 1 ton. Higher numbers cover more square footage."},{"term":"Zone","definition":"An independently controlled area of your home — e.g., living room vs. bedroom."}]', 'migration', NOW())
ON CONFLICT (key) DO NOTHING;
